// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnvbbpclvhldyfcrrwsl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhudmJicGNsdmhsZHlmY3Jyd3NsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzMTcyMzgsImV4cCI6MjA1ODg5MzIzOH0.ZSSF4iBf0LVVUzhEWTdAph5ZRD_uJW4xJbLRTin-7L0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);